import { Category } from './types/Category';

export const categorySeed: Category[] = [
    {
        id: '1',
        name: 'מחשבים ואלקטרוניקה',
        icon: '💻',
        color: '#4A90E2',
        type: 'product',
        translations: {
            en: 'Computers & Electronics',
        },
        relatedInterests: ['technology', 'gadgets'],
        tags: ['tech', 'electronics'],
        popularity: 0,
        usageCount: 0,
        isFeatured: true,
        sortOrder: 1,
        isActive: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'ריהוט ויד שנייה',
        icon: '🛋️',
        color: '#A0522D',
        type: 'product',
        translations: {
            en: 'Furniture & Second Hand',
        },
        relatedInterests: ['home', 'reuse'],
        tags: ['furniture', 'secondhand'],
        popularity: 0,
        usageCount: 0,
        isActive: true,
        sortOrder: 2,
        createdAt: new Date().toISOString(),
    },
    {
        id: '3',
        name: 'התייעצות רפואית',
        icon: '🩺',
        color: '#E74C3C',
        type: 'consultation',
        translations: {
            en: 'Medical Consultation',
        },
        relatedInterests: ['health', 'wellness'],
        tags: ['doctor', 'healthcare'],
        isFeatured: true,
        usageCount: 0,
        popularity: 0,
        isActive: true,
        sortOrder: 3,
        createdAt: new Date().toISOString(),
    },
    {
        id: '4',
        name: 'עבודות כלליות',
        icon: '🛠️',
        color: '#2ECC71',
        type: 'job',
        translations: {
            en: 'General Jobs',
        },
        relatedInterests: ['work', 'freelance'],
        tags: ['jobs', 'labor'],
        usageCount: 0,
        popularity: 0,
        isActive: true,
        sortOrder: 4,
        createdAt: new Date().toISOString(),
    },
    {
        id: '5',
        name: 'בקשת עזרה',
        icon: '🙏',
        color: '#F39C12',
        type: 'help',
        translations: {
            en: 'Help Request',
        },
        relatedInterests: ['community', 'support'],
        tags: ['help', 'need'],
        isFeatured: true,
        usageCount: 0,
        popularity: 0,
        isActive: true,
        sortOrder: 5,
        createdAt: new Date().toISOString(),
    },
    {
        id: '6',
        name: 'אירועים בקהילה',
        icon: '🎉',
        color: '#9B59B6',
        type: 'event',
        translations: {
            en: 'Community Events',
        },
        relatedInterests: ['events', 'social'],
        tags: ['event', 'community'],
        usageCount: 0,
        popularity: 0,
        isActive: true,
        sortOrder: 6,
        createdAt: new Date().toISOString(),
    },
];
